"""changed hero attributes

Revision ID: cf8328b31995
Revises: 296dbf21962c
Create Date: 2023-10-30 15:03:45.494960

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf8328b31995'
down_revision = '296dbf21962c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('heroes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(length=300), nullable=True))
        batch_op.drop_column('lore')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('heroes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lore', sa.VARCHAR(length=300), nullable=False))
        batch_op.drop_column('description')

    # ### end Alembic commands ###
